services:
  dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        BACKEND_API_URL: http://localhost:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000" # Express backend
      - "3000:3000" # React frontend
    environment:
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/urlshortener
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        BACKEND_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/urlshortener
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  pgdata:
